services:
  pdfocr:
    build: .
    image: pdfocr:latest
    volumes:
      # 현재 디렉토리를 컨테이너의 /work에 마운트 (로컬과 동일한 환경)
      - .:/work
    working_dir: /work
    # 사용 예시:
    # docker compose run --rm pdfocr /work/test/test_document.pdf -o /work/test/docker_output --keep-images -i /work/test/docker_images --lang eng+kor
